# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1585687432);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1585686952);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1585687072);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1585687312);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1585687192);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140715215148");
user_pref("browser.slowStartup.averageTime", 5029);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20140715215148");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":2}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1568223925452");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1585686893958");
user_pref("datareporting.policy.firstRunTime", "1568137525450");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 9363);
user_pref("datareporting.sessions.current.main", 155);
user_pref("datareporting.sessions.current.sessionRestored", 8121);
user_pref("datareporting.sessions.current.startTime", "1585691572481");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.3", "{\"s\":1585090839538,\"a\":37,\"t\":290,\"c\":false,\"m\":211,\"fp\":2966,\"sr\":2528}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1585179562481,\"a\":0,\"t\":5,\"c\":false,\"m\":221,\"fp\":2717,\"sr\":2408}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1585686831214,\"a\":19,\"t\":771,\"c\":true,\"m\":201,\"fp\":2239,\"sr\":2133}");
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1407427883000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-es-ES@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-ES@firefox.mozilla.org.xpi\",\"mtime\":1449742521000},\"langpack-es-MX@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-MX@firefox.mozilla.org.xpi\",\"mtime\":1449742521000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1407427633000,\"rdfTime\":1405462892000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1449742517000},\"langpack-es-CL@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-CL@firefox.mozilla.org.xpi\",\"mtime\":1449742521000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1449742517000},\"langpack-es-AR@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-AR@firefox.mozilla.org.xpi\",\"mtime\":1449742521000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140715215148");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1585691636);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52839);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1585691572);
user_pref("toolkit.telemetry.previousBuildID", "20140715215148");
